language: bash

sudo: required

services:
  - docker

## No tests so far
#before_install:
#  - sudo add-apt-repository ppa:duggan/bats --yes
#  - sudo apt-get update -q
#  - sudo apt-get install -q bats

script:
  - docker build -t scholzj/qpid-proton:travis .
## No tests so far
#  - bats tests.bats

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag scholzj/qpid-proton:travis docker.io/scholzj/qpid-proton:0.15.0; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push docker.io/scholzj/qpid-proton:0.15.0; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker tag scholzj/qpid-proton:travis docker.io/scholzj/qpid-proton:latest; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push docker.io/scholzj/qpid-proton:latest; fi
